/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingOrganizationRouteImport } from './routes/onboarding/organization'
import { Route as InviteTokenRouteImport } from './routes/invite/$token'
import { Route as AuthSsoRouteImport } from './routes/auth/sso'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AppLayoutRouteImport } from './routes/app/_layout'
import { Route as AppLayoutIndexRouteImport } from './routes/app/_layout/index'
import { Route as AppLayoutSettingsLayoutRouteImport } from './routes/app/_layout/settings/_layout'
import { Route as AppLayoutSettingsLayoutProfileRouteImport } from './routes/app/_layout/settings/_layout/profile'
import { Route as AppLayoutSettingsLayoutOrganizationRouteImport } from './routes/app/_layout/settings/_layout/organization'
import { Route as AppLayoutSettingsLayoutMembersRouteImport } from './routes/app/_layout/settings/_layout/members'

const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingOrganizationRoute = OnboardingOrganizationRouteImport.update({
  id: '/onboarding/organization',
  path: '/onboarding/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSsoRoute = AuthSsoRouteImport.update({
  id: '/auth/sso',
  path: '/auth/sso',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutRoute = AppLayoutRouteImport.update({
  id: '/app/_layout',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutIndexRoute = AppLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutSettingsLayoutRoute = AppLayoutSettingsLayoutRouteImport.update({
  id: '/settings/_layout',
  path: '/settings',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutSettingsLayoutProfileRoute =
  AppLayoutSettingsLayoutProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AppLayoutSettingsLayoutRoute,
  } as any)
const AppLayoutSettingsLayoutOrganizationRoute =
  AppLayoutSettingsLayoutOrganizationRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => AppLayoutSettingsLayoutRoute,
  } as any)
const AppLayoutSettingsLayoutMembersRoute =
  AppLayoutSettingsLayoutMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AppLayoutSettingsLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/app': typeof AppLayoutRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/sso': typeof AuthSsoRoute
  '/invite/$token': typeof InviteTokenRoute
  '/onboarding/organization': typeof OnboardingOrganizationRoute
  '/app/': typeof AppLayoutIndexRoute
  '/app/settings': typeof AppLayoutSettingsLayoutRouteWithChildren
  '/app/settings/members': typeof AppLayoutSettingsLayoutMembersRoute
  '/app/settings/organization': typeof AppLayoutSettingsLayoutOrganizationRoute
  '/app/settings/profile': typeof AppLayoutSettingsLayoutProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/sso': typeof AuthSsoRoute
  '/invite/$token': typeof InviteTokenRoute
  '/onboarding/organization': typeof OnboardingOrganizationRoute
  '/app': typeof AppLayoutIndexRoute
  '/app/settings': typeof AppLayoutSettingsLayoutRouteWithChildren
  '/app/settings/members': typeof AppLayoutSettingsLayoutMembersRoute
  '/app/settings/organization': typeof AppLayoutSettingsLayoutOrganizationRoute
  '/app/settings/profile': typeof AppLayoutSettingsLayoutProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/app/_layout': typeof AppLayoutRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/sso': typeof AuthSsoRoute
  '/invite/$token': typeof InviteTokenRoute
  '/onboarding/organization': typeof OnboardingOrganizationRoute
  '/app/_layout/': typeof AppLayoutIndexRoute
  '/app/_layout/settings/_layout': typeof AppLayoutSettingsLayoutRouteWithChildren
  '/app/_layout/settings/_layout/members': typeof AppLayoutSettingsLayoutMembersRoute
  '/app/_layout/settings/_layout/organization': typeof AppLayoutSettingsLayoutOrganizationRoute
  '/app/_layout/settings/_layout/profile': typeof AppLayoutSettingsLayoutProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/app'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/sso'
    | '/invite/$token'
    | '/onboarding/organization'
    | '/app/'
    | '/app/settings'
    | '/app/settings/members'
    | '/app/settings/organization'
    | '/app/settings/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/callback'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/sso'
    | '/invite/$token'
    | '/onboarding/organization'
    | '/app'
    | '/app/settings'
    | '/app/settings/members'
    | '/app/settings/organization'
    | '/app/settings/profile'
  id:
    | '__root__'
    | '/'
    | '/callback'
    | '/app/_layout'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/sso'
    | '/invite/$token'
    | '/onboarding/organization'
    | '/app/_layout/'
    | '/app/_layout/settings/_layout'
    | '/app/_layout/settings/_layout/members'
    | '/app/_layout/settings/_layout/organization'
    | '/app/_layout/settings/_layout/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CallbackRoute: typeof CallbackRoute
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthSsoRoute: typeof AuthSsoRoute
  InviteTokenRoute: typeof InviteTokenRoute
  OnboardingOrganizationRoute: typeof OnboardingOrganizationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/organization': {
      id: '/onboarding/organization'
      path: '/onboarding/organization'
      fullPath: '/onboarding/organization'
      preLoaderRoute: typeof OnboardingOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sso': {
      id: '/auth/sso'
      path: '/auth/sso'
      fullPath: '/auth/sso'
      preLoaderRoute: typeof AuthSsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_layout': {
      id: '/app/_layout'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_layout/': {
      id: '/app/_layout/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppLayoutIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/_layout/settings/_layout': {
      id: '/app/_layout/settings/_layout'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppLayoutSettingsLayoutRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/_layout/settings/_layout/profile': {
      id: '/app/_layout/settings/_layout/profile'
      path: '/profile'
      fullPath: '/app/settings/profile'
      preLoaderRoute: typeof AppLayoutSettingsLayoutProfileRouteImport
      parentRoute: typeof AppLayoutSettingsLayoutRoute
    }
    '/app/_layout/settings/_layout/organization': {
      id: '/app/_layout/settings/_layout/organization'
      path: '/organization'
      fullPath: '/app/settings/organization'
      preLoaderRoute: typeof AppLayoutSettingsLayoutOrganizationRouteImport
      parentRoute: typeof AppLayoutSettingsLayoutRoute
    }
    '/app/_layout/settings/_layout/members': {
      id: '/app/_layout/settings/_layout/members'
      path: '/members'
      fullPath: '/app/settings/members'
      preLoaderRoute: typeof AppLayoutSettingsLayoutMembersRouteImport
      parentRoute: typeof AppLayoutSettingsLayoutRoute
    }
  }
}

interface AppLayoutSettingsLayoutRouteChildren {
  AppLayoutSettingsLayoutMembersRoute: typeof AppLayoutSettingsLayoutMembersRoute
  AppLayoutSettingsLayoutOrganizationRoute: typeof AppLayoutSettingsLayoutOrganizationRoute
  AppLayoutSettingsLayoutProfileRoute: typeof AppLayoutSettingsLayoutProfileRoute
}

const AppLayoutSettingsLayoutRouteChildren: AppLayoutSettingsLayoutRouteChildren =
  {
    AppLayoutSettingsLayoutMembersRoute: AppLayoutSettingsLayoutMembersRoute,
    AppLayoutSettingsLayoutOrganizationRoute:
      AppLayoutSettingsLayoutOrganizationRoute,
    AppLayoutSettingsLayoutProfileRoute: AppLayoutSettingsLayoutProfileRoute,
  }

const AppLayoutSettingsLayoutRouteWithChildren =
  AppLayoutSettingsLayoutRoute._addFileChildren(
    AppLayoutSettingsLayoutRouteChildren,
  )

interface AppLayoutRouteChildren {
  AppLayoutIndexRoute: typeof AppLayoutIndexRoute
  AppLayoutSettingsLayoutRoute: typeof AppLayoutSettingsLayoutRouteWithChildren
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppLayoutIndexRoute: AppLayoutIndexRoute,
  AppLayoutSettingsLayoutRoute: AppLayoutSettingsLayoutRouteWithChildren,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CallbackRoute: CallbackRoute,
  AppLayoutRoute: AppLayoutRouteWithChildren,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthSsoRoute: AuthSsoRoute,
  InviteTokenRoute: InviteTokenRoute,
  OnboardingOrganizationRoute: OnboardingOrganizationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
